<?php


$plugin = array(
    'title' => t('front'),
    'category' => t('Columns: 3'),
    'icon' => 'front.png',
    'theme' => 'panels_front',
    'css' => 'front.css',
    'regions' => array(
        'top' => t('Top'),
        'full1' => t('full1'),
        'full2' => t('full2'),
        'left_icon' => t('Left _icon side'),
        'left' => t('Left side'),
        'right_icon' => t('Right _icon side'),
        'right' => t('Right side'),
        'full3' => t('full3'),
        'bot1' => t('Botton 1'),
        'bot2' => t('Botton 2'),

    ),
);

