<?php


$plugin = array(
    'title' => t('Project'),
	'category' => t('Columns: 3'),
    'icon' => 'project.png',
    'theme' => 'panels_project',
    'css' => 'project.css',
    'regions' => array(
      'top' => t('Top'),
      'left' => t('Left side'),
      'middle' => t('Middle column'),
      'middle_right' => t('Middle Right column'),
      'right' => t('Right side'),
      'bottom' => t('Bottom'),
      'bottom_right' => t('Bottom right'),
      'bot1' => t('Botton 1'),
      'bot2' => t('Botton 2'),
      'bot3' => t('Botton 3'),
      'bot4' => t('Botton 4')
    ),
  );

